version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 315438239075.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t shiv-ecr-repo:latest .
      - docker tag shiv-ecr-repo:latest 315438239075.dkr.ecr.us-east-1.amazonaws.com/shiv-ecr-repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 315438239075.dkr.ecr.us-east-1.amazonaws.com/shiv-ecr-repo:latest
